### ISSUE TITLE
Give each node a specific url

### ISSUE THREAD

**Issue by Thysrael** [ikoamu/publish-org-roam-ui#13]
Currently the entire org-roam-ui shares a single url, which makes it difficult to share a specific node like a blog. It would be much more efficient if each node was given a specific url.

This feature may not matter to local users, as there are good node search tools available on emacs locally. But on a website, this feature can be very useful.

Thank you very much for your persistent development! The user experience of the software you develop is getting better and better.

**Comment by ikoamu** [comment]
The screen can be displayed with a specific node displayed in the sidebar by specifying `#<node-id>` in the URL.

e.g. https://ikoamu.github.io/publish-org-roam-ui/#66ECE52E-2723-41B3-A4AB-6CEC507C1349

**Comment by Thysrael** [comment]
> The screen can be displayed with a specific node displayed in the sidebar by specifying `#<node-id>` in the URL.
> 
> e.g. https://ikoamu.github.io/publish-org-roam-ui/#66ECE52E-2723-41B3-A4AB-6CEC507C1349

That's so cool!
