### ISSUE TITLE
Disappearing Images: Not allowed to load local resource

### ISSUE THREAD

**Issue by Thysrael** [ikoamu/publish-org-roam-ui#14]
After one of the recent pushes, I realized that the images in the org-mode's were not displaying properly. After opening the browser console, the following error is reported:

```javascript
Not allowed to load local resource: file:///img/2024-04-11_08-19-52_screenshot.png
```
The link corresponding to this image looks like this in org-mode:

```org-mode
[[file:img/2024-04-11_08-19-52_screenshot.png]]
```

I'm guessing it's because of the `file:` words in the link. Because when I change the link to the following form, it displays the image properly:

```org-mode
[[img/2024-04-11_08-19-52_screenshot.png]]
```

But since I utilize org-download to download images, my links to images are basically in the form of `[[file:xxxx]]`.

Do you have any idea how to make the link with the word `file` work, as it did before. The link I'm testing with is [this one](https://thysrael.github.io/Roam-Site/#116303b7-7f7f-4513-9893-cc3f5ff32beb). By the way, your URL function works really well!

It doesn't matter if for some reason the fix doesn't work, I can replace all links without `file` and set org-download to not use `file`. Thanks for your continued development of this project!

**Comment by ikoamu** [comment]
Thanks for the report! I guess I didn't take the `file:` prefix into account.
Probably easy to fix. Please wait a bit!

**Comment by ikoamu** [comment]
@Thysrael 
Hi. I'm a little late in responding.
Please check the images that  `file:`  in theas they can now be displayed.

**Comment by Thysrael** [comment]
Woooooooo! That's awesome! Every image now can display very well.
