### ISSUE TITLE
Image width

### ISSUE THREAD

**Issue by sherlockes** [ikoamu/publish-org-roam-ui#16]
When I insert an image using [[[./img/test.png]] it adapts to the width of the tab so that it occupies the entire width of the tab. How can I set a maximum width for the image?

I tried inserting this but it doesn't work.

#+ATTR_HTML: :width 300px
[[./img/org-roam.png]]

**Comment by ikoamu** [comment]
Hello. 
Unfortunately the `org-html-*` option is not supported by the original [org-roam-ui](https://github.com/org-roam/org-roam-ui) either.
But if you want to publish a page, it would be better to have this option.
I will try to implement it if it seems feasible.

Thanks!

**Comment by ikoamu** [comment]
Support for the #+ATTR_HTML keyword has been added!
If you encounter any problems, please open an issue.
