### ISSUE TITLE
Application error: a client-side exception has occurred

### ISSUE THREAD

**Issue by sherlockes** [ikoamu/publish-org-roam-ui#18]
The generated website loads correctly, but after a few clicks the following error appears:

Application error: a client-side exception has occurred (see the browser console for more information).

The generated website loads correctly, but after a few clicks the following error appears: If we go to the console it shows us this error in several lines: 

TypeError: a.slice is not a function

Thks

**Comment by ikoamu** [comment]
I'm sorry, support for the `ATTR_HTML` keyword(#16) seems to have failed. I've reverted the implementation once, so please check it again.

**Comment by sherlockes** [comment]
Okay, now it works properly.
