### ISSUE TITLE
Search feature performance improvement

### ISSUE THREAD

**Issue by thargosu** [ikoamu/publish-org-roam-ui#24]
Hi and thanks again for all your work on this great project.

I have an org-roam dataset of about 3700 nodes and I can notice the search feature is having quite a hard time when trying to do live completion.

I have looked at the way it is currently done and if I am correct there is code that generates a JSON file with all the entries (`generate_searchdata.mjs`). Then the search feature will use the JSON file to do its live completion.

I was wondering if we could improve the performances by using the binary version of the JSON format, i.e. BSON file format instead.

It seems there is a JS library available to do this. 

```js
    import BSON from 'bson';
//...
    const bsonData = BSON.serialize(searchData);
```

You can test my network of nodes at https://elitedangereuse.github.io/LoreExplorer/ and check the search performances there.
Other than the search feature, the rest is super smooth.

This is just a suggestion, and you might come up with a far better implementation.

I was also considering the use of a **xapian** index and I can see there is a Node implementation of it: https://github.com/mtibeica/node-xapian#readme

Thanks a lot for considering this improvement.

**Comment by ikoamu** [comment]
@thargosu 
Thank you for proposing such an excellent improvement idea!
The BSON format idea seems like something we could try right away, so I'll check to see if it's effective.
I've also thought of two improvement ideas for this issue:

###  1. Utilize Fuse.js Indexing
The search function in org-roam-ui is implemented using the Fuse.js library. This library has a feature to create an index in advance from the JSON file used for searching, which can improve performance.
I think this might be the most efficient way to expect performance improvement.
https://www.fusejs.io/api/indexing.html

### 2. Allow selection of search targets
Currently, the search is performed on all titles, tags, and contents of nodes that match the input word.
It's likely that searching the content takes the most time, so in cases where users only want to search titles or tags, we should be able to save that time.
I'm thinking that performance could be improved by limiting the search targets with checkboxes or similar controls below the search word text field.


Please let me know if you have any thoughts on these ideas.
Thank you for contributing to this open-source project!

**Comment by thargosu** [comment]
Thanks for your quick answer!
I believe having an index can greatly help. I didn't know Fuse.js, but from what I read in the link you shared, it seems like the way to go :+1: .

Regarding the search targets, I think it's a great idea for many reasons. It can indeed improve the efficiency of the search algorithm, and it provides a great way to reduce the completion list of suggestions for the user. Finally, it raises awareness on the existence of tags for less experimented users, which is great because it's a powerful feature.

Thanks a lot for working on this!

**Comment by ikoamu** [comment]
As #26 and https://github.com/ikoamu/org-roam-ui/pull/14 have been merged, I'm closing this issue for now.
If any problems occur again, please either reopen this issue or create a new one.
Thank you！
