### ISSUE TITLE
Org-verbatim style

### ISSUE THREAD

**Issue by Thysrael** [ikoamu/publish-org-roam-ui#25]
I noticed that only the `org-code` had a special inline style, however the `org-verbatim` didn't have it. The src looks like that:

```org-mode
~chroot~ 需要指定根目录（也就是 =mnt= ）和要运行的命令，这个命令是在新的根文件系统下的。
```

The deployment results looks like that:

![image](https://github.com/user-attachments/assets/3e08c182-dbba-4112-952b-4e9a53740d79)

The `=mnt=` is same as normal text. 

Is it convenient to add a style for `org-verbatim` to distinguish it? Thanks for your development.

**Comment by hermanhel** [comment]
From my inspection:
+ in org-roam-ui, both ~~ and == are code tags., ~~ have class inline-code, == have class inline-verbatim. But they don't really look different or anything.
+ in publish-org-roam-ui, ~~ is code tag with a generated css which I'm not sure where it is from, whereas == is just text.
+ a relevent file is [ikoamu/org-roam-ui/util/processOrg.tsx](https://github.com/ikoamu/org-roam-ui/blob/265f98b15ef479e7b7491f70ac8ca2b62ae4e758/util/processOrg.tsx#L200) where I can see that some mapping is going on, and this file is modified in ikoamu's fork.

**Comment by ikoamu** [comment]
@Thysrael  Sorry for the late reply!
I've modified the org-verbatim text to display in the same style as org-code, so please check it out.

@hermanhel Thank you for your comment. It helped with the modification!

**Comment by Thysrael** [comment]
> @Thysrael Sorry for the late reply! I've modified the org-verbatim text to display in the same style as org-code, so please check it out.
> 
> @hermanhel Thank you for your comment. It helped with the modification!

Thank you very much
