### ISSUE TITLE
(could not find node)

### ISSUE THREAD

**Issue by Titikomba** [ikoamu/publish-org-roam-ui#28]
Hi,
First of all, thank you very much for developing this :)

I run the script locally. The database has been found and launching index.html reveals the expected structure.
Sadly, all the nodes are empty, the message `(could not find node)` being displayed instead...
Could this behaviour be caused by the internal structure of my roam-dir ?
```
.
├── 01_references
│   ...
│   ├── 20241006163832-ag_l90_basic_local_aligment_search_tool.org
│   └── 20241006164507-kent02_blat_the_blast_like_alignment_tool.org
├── 02_concepts
│   ├── 20240927082424-kmer.org
│   ...
...
├── 06_assets
│   └── yddb15_framework.jpg
└── org-roam.db
```

Best,

**Comment by ikoamu** [comment]
@Titikomba Hello. Thank you for creating the issue!

To help resolve this problem, I have two questions:
- Are you using GitHub Actions for page generation? (Or are you using local.sh?)
- Could you please explain the steps to save node files in a custom directory?
  (Typically, when creating files using org-roam-node-find, they are created directly under the org-roam-directory, I believe.)
  
Thank you.

**Comment by Titikomba** [comment]
I'm using ./local.sh.
Here is the part of my config responsible for this clustering of files
```lisp
  (org-roam-capture-templates
   '(
     ("r" "reference note" plain (file "~/Documents/01_research/02_notes/05_templates/template_reference.org")
      :if-new (file+head "01_references/%<%Y%m%d%H%M%S>-${slug}.org" "#+Title: ${title}\n")
      :unnarrowed t)
     ("c" "concept" plain (file "~/Documents/01_research/02_notes/05_templates/template_concept.org")
      :if-new (file+head "02_concepts/%<%Y%m%d%H%M%S>-${slug}.org" "#+title: ${title}\n")
      :unnarrowed t)
     ("a" "argument" plain (file "~/Documents/01_research/02_notes/05_templates/template_argument.org")
      :if-new (file+head "03_arguments/%<%Y%m%d%H%M%S>-${slug}.org" "#+title: ${title}\n")
      :unnarrowed t)
     ("t" "track" plain (file "~/Documents/01_research/02_notes/05_templates/template_track.org")
      :if-new (file+head "04_tracks/%<%Y%m%d%H%M%S>-${slug}.org" "#+title: ${title}\n")
      :unnarrowed t)))
```

Best,

**Comment by thargosu** [comment]
Hi,

Did you start a web server to access the generated website or are you directly accessing the index with your browser via file:///path/to/index ?

**Comment by Titikomba** [comment]
Hi,
I directly (perhaps naively) opened index.html

Best,

**Comment by hermanhel** [comment]
I can confirm that my generated website served succesfully on https://hermanhel.codeberg.page/braindump-ui/ have the same behaviour when open locally with file:///path/to/index in firefox.  (could not find node)

I tried npx serve, npx http-server, next dev, next start, none worked. npx http-server will crash when index.html is opened, next dev and start failed to run.

**Comment by Titikomba** [comment]
I followed @.hermanhel suggestion, and this indeed create a localhost instance with the roam interface accessible.
The `(could not find node)` does not appear anymore **but** `(no content yet)` is here instead...

**Comment by ikoamu** [comment]
@Titikomba 
Could you please check two things for investigation?

- Are nodes created directly under the `org-roam-directory` also not displayed?
- When generating the site using `local.sh`, if you modify the `next.config.js` file in the cloned `org-roam-ui` repository as follows, are the nodes still not displayed?

```diff
const fs = require('fs')

// const d3packages = fs.readdirSync('node_modules').filter((name) => name.startsWith('d3-'))
// const withTM = require('next-transpile-modules')(d3packages)
/**
 * @type {import('next').NextConfig}
 */
const nextConfig =  {
  distDir: 'build',
  images: {
    domains: ['localhost'],
    loader: 'custom',
  },
- assetPrefix: './', // delete this line
  output: "export",
  distDir: 'standalone/out/',
}

module.exports = nextConfig
```

**Comment by leo-ackermann** [comment]
@ikoamu It did the job for almost all nodes! Thank you :)
Note that I needed to use `npx serve` as indicated earlier.

I'm responsible for the last ones: my setup is a bit special. I use symlinks for some nodes (I trick org-roam with `(setq find-file-visit-truename t)`): typically, experiment notes that lie within an experiment folder (with data, scripts, etc). Symlinks to those folders appear in org-roam subfolders. Hence:
- sure I'll be super happy if those could also be found while generating the website, but
- I'll completely understand you prefer to ignore this edge case, and close the issue 😇 

Best,

**Comment by ikoamu** [comment]
I apologize. At this point, I cannot think of a solution to handle such a special case.
If you have any ideas, please feel free to create an issue. Thank you!
