### ISSUE TITLE
Images are not showing with ./local.sh

### ISSUE THREAD

**Issue by leo-ackermann** [ikoamu/publish-org-roam-ui#32]
Hi 👋,
I observed images are not displayed with `./local.sh`.

I tried numerous org syntax, that all work with org-roam-ui
```
[[~/Documents/01_research/02_notes/06_assets/yddb15_framework.png]]
[[file:~/Documents/01_research/02_notes/06_assets/yddb15_framework.png]]
[[../06_assets/yddb15_framework.png]]
[[file:../06_assets/yddb15_framework.png]]
[[file:../06_assets/yddb15_framework.png][Description]]
```
but I only obtain blank images
<img width="1768" alt="image" src="https://github.com/user-attachments/assets/c61e37ae-bdb1-440e-9f2b-5dc078b8d5b8">

-----
My file organisation is as follow:
```
.
├── 01_references
│   ...
│   ├── 20241006163832-ag_l90_basic_local_aligment_search_tool.org
│   └── 20241006164507-kent02_blat_the_blast_like_alignment_tool.org
├── 02_concepts
│   ├── 20240927082424-kmer.org
│   ...
...
├── 06_assets
│   └── yddb15_framework.jpg
└── org-roam.db
```

**Comment by ikoamu** [comment]
publish-org-roam-ui is designed with the assumption that org files and resources like images are managed within a single repository.
Therefore, currently only image files stored in the img directory under org-roam-dir will be displayed.

- README.md https://github.com/ikoamu/publish-org-roam-ui?tab=readme-ov-file#show-image
- Relevant code https://github.com/ikoamu/publish-org-roam-ui/blob/23fbb1f5cb84c3c403c259d045dc60d3b116bc4f/local.sh#L6

Please feel free to comment if you have any questions.
Thank you!

**Comment by leo-ackermann** [comment]
I found it unclear from the README that it was the **only** way to display images (for now).
In any case, customising `ROAM_IMG_PATH` suits my needs 😊 
Thanks!
