### ISSUE TITLE
How to set favicon for web page

### ISSUE THREAD

**Issue by Thysrael** [ikoamu/publish-org-roam-ui#33]
Sorry to borther you. I noticed that the example website has a favicon, but my own website does not. I want to know how to set it up.

Here is the contrast, The first is the example, and the second is mine:

![image](https://github.com/user-attachments/assets/eb9a3e24-b0fc-4815-83c8-8dc3cab6226f)

**Comment by ikoamu** [comment]
Unfortunately, publish-org-roam-ui does not yet have a feature to freely set favicons. 
This seems to be due to the fact that https://ikoamu.github.io/ is generated using [Gatsby.
](https://www.gatsbyjs.com/)

**Comment by Thysrael** [comment]
Thank you for replying me! It doesn't be a big matter.
